export type Project = {
  slug: string;
  name: string;
  image: string;
  type: string;
  typeTh: string;
  province: string;
  provinceTh: string;
  location: string;
  locationTh: string;
  year: string;
  developer: string;
  scope: string[];
  descriptionTh: string;
  highlightsTh: string[];
};

export const projects: Project[] = [
  {
    slug: "kave-bangsaen",
    name: "KAVE BANGSAEN",
    image: "/images/project-kave-bangsaen.png",
    type: "Low-rise Condominium",
    typeTh: "คอนโดมิเนียม Low-rise",
    province: "Chonburi",
    provinceTh: "ชลบุรี",
    location: "Saen Suk, Mueang Chonburi",
    locationTh: "ตำบลแสนสุข อำเภอเมืองชลบุรี จังหวัดชลบุรี",
    year: "2025",
    developer: "AssetWise",
    scope: ["Aluminium Door & Window", "Glass Wall", "Railing"],
    descriptionTh:
      "โครงการคอนโดมิเนียม Low-rise ขนาดใหญ่ย่านบางแสน ประกอบด้วยอาคาร 8 หลัง สูง 4 ชั้น รวมกว่า 974 ยูนิต ตั้งอยู่ใกล้มหาวิทยาลัยบูรพา โดดเด่นด้วยสระว่ายน้ำและพื้นที่ส่วนกลางขนาดใหญ่ท่ามกลางสวนสีเขียว K.S.Manufactory (1991) รับผิดชอบงานติดตั้งประตู–หน้าต่างอลูมิเนียม ผนังกระจก และราวกันตกทั้งโครงการ",
    highlightsTh: [
      "8 อาคาร สูง 4 ชั้น รวมเกือบ 1,000 ยูนิต",
      "ติดกับมหาวิทยาลัยบูรพา ใกล้หาดบางแสน",
      "งานประตู–หน้าต่างอลูมิเนียมและระบบกระจกครบวงจร",
    ],
  },
  {
    slug: "so-kaset",
    name: "SO KASET",
    image: "/images/project-so-kaset.png",
    type: "High-rise Condominium",
    typeTh: "คอนโดมิเนียม High-rise",
    province: "Bangkok",
    provinceTh: "กรุงเทพมหานคร",
    location: "Sena Nikhom, Chatuchak",
    locationTh: "แขวงเสนานิคม เขตจตุจักร กรุงเทพมหานคร",
    year: "2025",
    developer: "Origin Property",
    scope: [
      "Unitized Curtain Wall",
      "Aluminium Door & Window",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "โครงการคอนโดมิเนียม High-rise 23 ชั้น ติดสถานี BTS แยกเกษตร ใกล้มหาวิทยาลัยเกษตรศาสตร์ พัฒนาโดย Origin Property ภายใต้แบรนด์ SO Origin ทีม K.S.Manufactory (1991) ดูแลงานเปลือกอาคารกระจกอลูมิเนียมทั้งโครงการ",
    highlightsTh: [
      "อาคารสูง 23 ชั้น",
      "ติด BTS แยกเกษตร",
      "ใกล้มหาวิทยาลัยเกษตรศาสตร์",
    ],
  },
  {
    slug: "the-origin-sukhumvit-e22",
    name: "THE ORIGIN Sukhumvit E22 Station",
    image: "/images/project-the-origin.png",
    type: "High-rise Condominium",
    typeTh: "คอนโดมิเนียม High-rise",
    province: "Samut Prakan",
    provinceTh: "สมุทรปราการ",
    location: "Pak Nam, Mueang Samut Prakan",
    locationTh: "ถนนสายลวด ตำบลปากน้ำ อำเภอเมืองสมุทรปราการ",
    year: "2024",
    developer: "Origin Property",
    scope: [
      "Unitized Curtain Wall",
      "Aluminium Door & Window",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "คอนโดมิเนียมอาคารสูง 31 ชั้น รวม 998 ยูนิต ตั้งอยู่ห่างจากสถานี BTS สายลวด (E22) เพียง 222 เมตร ใช้ระบบ Unitized Curtain Wall เต็มอาคาร K.S.Manufactory (1991) ดูแลงานออกแบบ ผลิต และติดตั้งระบบกระจกอลูมิเนียมทั้งระบบ ส่งมอบงานได้ตรงตามมาตรฐานสากล",
    highlightsTh: [
      "อาคารสูง 31 ชั้น 998 ยูนิต",
      "ติด BTS สายลวด (E22)",
      "ระบบ Unitized Curtain Wall เต็มอาคาร",
    ],
  },
  {
    slug: "vay-amata",
    name: "VAY AMATA",
    image: "/images/project-vay-amata.png",
    type: "Low-rise Residential Condominium",
    typeTh: "คอนโดมิเนียม Low-rise",
    province: "Chonburi",
    provinceTh: "ชลบุรี",
    location: "Ban Kao, Phan Thong, Chonburi",
    locationTh: "ตำบลบ้านเก่า อำเภอพานทอง จังหวัดชลบุรี",
    year: "2024",
    developer: "Sansiri",
    scope: ["Aluminium Door & Window", "Glass Wall", "Railing"],
    descriptionTh:
      "คอนโดมิเนียม Low-rise 2 อาคาร สูง 8 ชั้น รวม 552 ยูนิต ใกล้นิคมอุตสาหกรรมอมตะนคร พัฒนาโดย Sansiri มุ่งเน้นตอบโจทย์พนักงานและผู้บริหารในพื้นที่ งานติดตั้งประตู–หน้าต่างอลูมิเนียม และระบบผนังกระจกโดย K.S.Manufactory (1991)",
    highlightsTh: [
      "2 อาคาร 8 ชั้น 552 ยูนิต",
      "ใกล้นิคมอุตสาหกรรมอมตะนคร",
      "โครงการคุณภาพจาก Sansiri",
    ],
  },
  {
    slug: "mira-monte-huahin",
    name: "MIRA MONTE HUAHIN",
    image: "/images/project-mira-monte-huahin.png",
    type: "Residential Condominium",
    typeTh: "คอนโดมิเนียมตากอากาศ",
    province: "Prachuap Khiri Khan",
    provinceTh: "ประจวบคีรีขันธ์",
    location: "Hua Hin, Prachuap Khiri Khan",
    locationTh: "ตำบลหัวหิน อำเภอหัวหิน จังหวัดประจวบคีรีขันธ์",
    year: "2024",
    developer: "Huahin Supsiri Property",
    scope: ["Aluminium Door & Window", "Glass Wall", "Railing"],
    descriptionTh:
      "โครงการคอนโดมิเนียมตากอากาศในหัวหิน สูง 8 ชั้น 115 ยูนิต ภายใต้แนวคิด Mira (ทะเล) + Monte (ขุนเขา) ที่นำเสน่ห์ของทะเลและขุนเขาไว้ในที่เดียว งานติดตั้งประตู–หน้าต่างอลูมิเนียมและผนังกระจกที่ต้องทนต่อสภาพอากาศชายทะเลโดย K.S.Manufactory (1991)",
    highlightsTh: [
      "8 ชั้น 115 ยูนิต",
      "คอนโดตากอากาศในหัวหิน",
      "ระบบทนความเค็มและสภาพอากาศชายทะเล",
    ],
  },
  {
    slug: "atmoz-sriracha",
    name: "ATMOZ SRIRACHA",
    image: "/images/project-atmoz-sriracha.png",
    type: "Low-rise Condominium",
    typeTh: "คอนโดมิเนียม Low-rise",
    province: "Chonburi",
    provinceTh: "ชลบุรี",
    location: "Thung Sukhla, Si Racha, Chonburi",
    locationTh: "ตำบลทุ่งสุขลา อำเภอศรีราชา จังหวัดชลบุรี",
    year: "2023",
    developer: "AssetWise",
    scope: ["Aluminium Door & Window", "Glass Wall", "Railing"],
    descriptionTh:
      "คอนโดมิเนียม Low-rise 3 อาคาร สูง 8 ชั้น รวม 539 ยูนิต ตั้งอยู่ริมถนนสุขุมวิท ตรงข้ามมหาวิทยาลัยเกษตรศาสตร์ วิทยาเขตศรีราชา บนเนื้อที่เกือบ 4 ไร่ K.S.Manufactory (1991) รับงานติดตั้งเปลือกอาคารอลูมิเนียม–กระจกทั้งโครงการ",
    highlightsTh: [
      "3 อาคาร 8 ชั้น รวม 539 ยูนิต",
      "ตรงข้ามมหาวิทยาลัยเกษตรศาสตร์ ศรีราชา",
      "ทำเลริมถนนสุขุมวิท",
    ],
  },
  {
    slug: "modiz-rhyme-ramkhamhaeng",
    name: "Modiz Rhyme Ramkhamhaeng",
    image: "/images/project-modiz-rhyme-ramkhamhaeng.png",
    type: "High-rise Condominium",
    typeTh: "คอนโดมิเนียม High-rise",
    province: "Bangkok",
    provinceTh: "กรุงเทพมหานคร",
    location: "Hua Mak, Bang Kapi",
    locationTh: "แขวงหัวหมาก เขตบางกะปิ กรุงเทพมหานคร",
    year: "2023",
    developer: "AssetWise",
    scope: [
      "Unitized Curtain Wall",
      "Aluminium Door & Window",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "คอนโดมิเนียมอาคารสูง 30 ชั้น รวม 555 ยูนิต ตรงข้ามมหาวิทยาลัยรามคำแหง ใกล้สถานี MRT รามคำแหง พัฒนาโดย AssetWise ที่มาพร้อมสิ่งอำนวยความสะดวกครบครัน งาน K.S.Manufactory (1991) ครอบคลุมระบบเปลือกอาคารกระจกอลูมิเนียมทั้งโครงการ",
    highlightsTh: [
      "อาคารสูง 30 ชั้น 555 ยูนิต",
      "ใกล้ MRT รามคำแหง",
      "ตรงข้ามมหาวิทยาลัยรามคำแหง",
    ],
  },
  {
    slug: "soho-bangkok-ratchada",
    name: "SOHO Bangkok Ratchada",
    image: "/images/project-soho-bangkok-ratchada.png",
    type: "High-rise Loft Condominium",
    typeTh: "คอนโดมิเนียมแนว Loft",
    province: "Bangkok",
    provinceTh: "กรุงเทพมหานคร",
    location: "Huai Khwang, Bangkok",
    locationTh: "แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพมหานคร",
    year: "2023",
    developer: "Origin Property",
    scope: [
      "Unitized Curtain Wall",
      "Aluminium Door & Window",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "คอนโดมิเนียม High-rise สูง 24 ชั้น 341 ยูนิต ภายใต้คอนเซ็ปต์ Small Office & Home (SOHO) ใกล้ MRT ห้วยขวาง พัฒนาโดย Origin Property ทีม K.S.Manufactory (1991) ดูแลงานเปลือกอาคารกระจกอลูมิเนียมทั้งโครงการ",
    highlightsTh: [
      "อาคารสูง 24 ชั้น 341 ยูนิต",
      "ใกล้ MRT ห้วยขวาง",
      "แนวคิด Small Office & Home (Loft)",
    ],
  },
  {
    slug: "hampton-sriracha",
    name: "Hampton Sriracha",
    image: "/images/project-hampton-sriracha.png",
    type: "High-rise Condominium",
    typeTh: "คอนโดมิเนียม High-rise",
    province: "Chonburi",
    provinceTh: "ชลบุรี",
    location: "Si Racha, Chonburi",
    locationTh: "ตำบลศรีราชา อำเภอศรีราชา จังหวัดชลบุรี",
    year: "2023",
    developer: "Origin Property × Dusit",
    scope: [
      "Unitized Curtain Wall",
      "Aluminium Door & Window",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "The Hampton Sriracha คอนโดมิเนียม High-rise สูง 26 ชั้น 468 ยูนิต ในย่านศรีราชา พัฒนาโดย Origin Property ร่วมกับกลุ่มดุสิต เน้นตอบโจทย์ผู้บริหารและคนทำงานในเขตอีอีซี ทีม K.S.Manufactory (1991) ดูแลงานเปลือกอาคารอลูมิเนียม–กระจกครบระบบ",
    highlightsTh: [
      "อาคารสูง 26 ชั้น 468 ยูนิต",
      "ใจกลางศรีราชา ใกล้ทะเลและเขตอีอีซี",
      "ระบบเปลือกอาคารเกรด Hospitality",
    ],
  },
  {
    slug: "monte-rangsit-campus",
    name: "MONTE RANGSIT CAMPUS",
    image: "/images/project-monte-rangsit.png",
    type: "Campus-style Condominium",
    typeTh: "คอนโดมิเนียมแคมปัส",
    province: "Pathum Thani",
    provinceTh: "ปทุมธานี",
    location: "Lak Hok, Mueang Pathum Thani",
    locationTh: "ตำบลหลักหก อำเภอเมืองปทุมธานี จังหวัดปทุมธานี",
    year: "2022",
    developer: "Capital G Development",
    scope: ["Aluminium Door & Window", "Stickwall System", "Railing"],
    descriptionTh:
      "คอนโดมิเนียมไลฟ์สไตล์แคมปัสติดมหาวิทยาลัยรังสิต สูง 8 ชั้น รวม 545 ยูนิต ออกแบบสำหรับนักศึกษาและบุคลากรที่ต้องการที่พักคุณภาพใกล้มหาวิทยาลัย ทีมงาน K.S.Manufactory (1991) ดูแลงานประตู–หน้าต่างอลูมิเนียม ระบบ Stickwall และราวกันตก ตั้งแต่เริ่มจนส่งมอบ",
    highlightsTh: [
      "สูง 8 ชั้น 545 ยูนิต",
      "ติดมหาวิทยาลัยรังสิต เดินทางสะดวก",
      "งานติดตั้งประตู–หน้าต่าง และ Stickwall System",
    ],
  },
  {
    slug: "knightsbridge-sukhumvit-theparak",
    name: "KnightsBridge Sukhumvit-Theparak",
    image: "/images/project-knightsbridge-sukhumvit-theparak.png",
    type: "High-rise Condominium",
    typeTh: "คอนโดมิเนียม High-rise",
    province: "Samut Prakan",
    provinceTh: "สมุทรปราการ",
    location: "Thepharak, Mueang Samut Prakan",
    locationTh: "ตำบลเทพารักษ์ อำเภอเมืองสมุทรปราการ",
    year: "2022",
    developer: "Origin Property",
    scope: [
      "Unitized Curtain Wall",
      "Aluminium Door & Window",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "คอนโดมิเนียม High-rise สูง 35 ชั้น รวม 474 ยูนิต ภายใต้แบรนด์ KnightsBridge ของ Origin Property ตั้งอยู่บนถนนสุขุมวิทย่านเทพารักษ์ ใกล้ทางด่วนและเส้นทางเชื่อมต่อกรุงเทพฯ K.S.Manufactory (1991) ดูแลงานเปลือกอาคารทั้งระบบ",
    highlightsTh: [
      "อาคารสูง 35 ชั้น 474 ยูนิต",
      "ย่านสุขุมวิท–เทพารักษ์",
      "ระบบ Unitized Curtain Wall",
    ],
  },
  {
    slug: "kensington-rayong",
    name: "Kensington Rayong",
    image: "/images/project-kensington-rayong.png",
    type: "Low-rise Condominium",
    typeTh: "คอนโดมิเนียม Low-rise",
    province: "Rayong",
    provinceTh: "ระยอง",
    location: "Noen Phra, Mueang Rayong",
    locationTh: "ตำบลเนินพระ อำเภอเมืองระยอง จังหวัดระยอง",
    year: "2022",
    developer: "Origin EEC",
    scope: ["Aluminium Door & Window", "Glass Wall", "Railing"],
    descriptionTh:
      "คอนโดมิเนียม Low-rise ในย่านเมืองระยอง 4 อาคาร สูง 8 ชั้น พัฒนาโดย Origin EEC ภายใต้โครงการ Origin Smart City Rayong ตอบโจทย์พนักงานในพื้นที่เขตอีอีซี งาน K.S.Manufactory (1991) ครอบคลุมการติดตั้งเปลือกอาคารครบวงจร",
    highlightsTh: [
      "4 อาคาร สูง 8 ชั้น",
      "ส่วนหนึ่งของ Origin Smart City Rayong",
      "ใกล้เขตอีอีซีและนิคมอุตสาหกรรม",
    ],
  },
  {
    slug: "notting-hill-rayong",
    name: "Notting Hill Rayong",
    image: "/images/project-notting-hill-rayong.png",
    type: "High-rise Condominium",
    typeTh: "คอนโดมิเนียม High-rise",
    province: "Rayong",
    provinceTh: "ระยอง",
    location: "Noen Phra, Mueang Rayong",
    locationTh: "ตำบลเนินพระ อำเภอเมืองระยอง จังหวัดระยอง",
    year: "2021",
    developer: "Origin EEC",
    scope: [
      "Unitized Curtain Wall",
      "Aluminium Door & Window",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "คอนโดมิเนียม High-rise สูง 34 ชั้น 537 ยูนิต ตึกสูงที่สุดในระยอง พัฒนาโดย Origin EEC ภายใต้แบรนด์ Notting Hill ตั้งอยู่ใจกลางเมืองระยอง ใกล้พื้นที่เขตอีอีซี K.S.Manufactory (1991) รับผิดชอบงานระบบ Curtain Wall และประตู–หน้าต่างอลูมิเนียม",
    highlightsTh: [
      "อาคารสูง 34 ชั้น 537 ยูนิต",
      "ตึกสูงที่สุดในระยอง",
      "ใจกลางเมือง ใกล้เขตอีอีซี",
    ],
  },
  {
    slug: "knightsbridge-collage-sukhumvit-107",
    name: "KnightsBridge Collage Sukhumvit 107",
    image: "/images/project-knightsbridge-college-sukhumvit-107.png",
    type: "High-rise Condominium",
    typeTh: "คอนโดมิเนียม High-rise",
    province: "Samut Prakan",
    provinceTh: "สมุทรปราการ",
    location: "Sam Rong Nuea, Mueang Samut Prakan",
    locationTh: "ถนนสุขุมวิท 107 ตำบลสำโรงเหนือ อำเภอเมืองสมุทรปราการ",
    year: "2021",
    developer: "Origin Property",
    scope: [
      "Unitized Curtain Wall",
      "Aluminium Door & Window",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "คอนโดมิเนียม High-rise สูง 28 ชั้น 303 ยูนิต บนถนนสุขุมวิท 107 ใกล้ BTS แบริ่ง เชื่อมต่อกรุงเทพฯ ได้อย่างสะดวก พัฒนาโดย Origin Property ภายใต้แบรนด์ KnightsBridge Collage ทีม K.S.Manufactory (1991) ดูแลงานเปลือกอาคารทั้งระบบ",
    highlightsTh: [
      "อาคารสูง 28 ชั้น 303 ยูนิต",
      "ใกล้ BTS แบริ่ง",
      "ระบบ Unitized Curtain Wall",
    ],
  },
  {
    slug: "kensington-sukhumvit-theparak",
    name: "Kensington Sukhumvit-Theparak",
    image: "/images/project-kensington-sukhumvit-theparak.png",
    type: "Twin High-rise Condominium",
    typeTh: "คอนโดมิเนียม High-rise (2 อาคาร)",
    province: "Samut Prakan",
    provinceTh: "สมุทรปราการ",
    location: "Thepharak, Mueang Samut Prakan",
    locationTh: "ตำบลเทพารักษ์ อำเภอเมืองสมุทรปราการ",
    year: "2020",
    developer: "Origin Property",
    scope: [
      "Unitized Curtain Wall",
      "Aluminium Door & Window",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "คอนโดมิเนียม High-rise 2 อาคาร อาคาร A สูง 38 ชั้น และอาคาร B สูง 35 ชั้น ย่านสุขุมวิท–เทพารักษ์ พัฒนาโดย Origin Property ภายใต้แบรนด์ Kensington K.S.Manufactory (1991) ดูแลงานเปลือกอาคารทั้งสองตึกอย่างละเอียด",
    highlightsTh: [
      "2 อาคาร สูง 38 และ 35 ชั้น",
      "ย่านเทพารักษ์–สุขุมวิท",
      "เปลือกอาคารเกรดไฮไรส์ทั้งสองตึก",
    ],
  },
  {
    slug: "knightsbridge-prime-ratchayothin",
    name: "KnightsBridge Prime Ratchayothin",
    image: "/images/project-knightsbridge-prime-ratchayothin.png",
    type: "High-rise Condominium",
    typeTh: "คอนโดมิเนียม High-rise",
    province: "Bangkok",
    provinceTh: "กรุงเทพมหานคร",
    location: "Chatuchak, Bangkok",
    locationTh: "แขวงจตุจักร เขตจตุจักร กรุงเทพมหานคร",
    year: "2020",
    developer: "Origin Property",
    scope: [
      "Unitized Curtain Wall",
      "Aluminium Door & Window",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "คอนโดมิเนียม High-rise สูง 36 ชั้น 333 ยูนิต ย่านรัชโยธิน ใกล้ BTS รัชโยธิน พัฒนาโดย Origin Property ภายใต้แบรนด์ KnightsBridge Prime K.S.Manufactory (1991) รับผิดชอบงานระบบ Curtain Wall และประตู–หน้าต่างอลูมิเนียม",
    highlightsTh: [
      "อาคารสูง 36 ชั้น 333 ยูนิต",
      "ใกล้ BTS รัชโยธิน",
      "แบรนด์ KnightsBridge Prime",
    ],
  },
  {
    slug: "knightsbridge-kaset-society",
    name: "KnightsBridge Kaset-Society",
    image: "/images/project-knightbridge-kaset-society.png",
    type: "High-rise Condominium",
    typeTh: "คอนโดมิเนียม High-rise",
    province: "Bangkok",
    provinceTh: "กรุงเทพมหานคร",
    location: "Sena Nikhom, Chatuchak",
    locationTh: "แขวงเสนานิคม เขตจตุจักร กรุงเทพมหานคร",
    year: "2020",
    developer: "Origin Property",
    scope: [
      "Unitized Curtain Wall",
      "Aluminium Door & Window",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "คอนโดมิเนียม High-rise 2 อาคาร 20 ชั้น และ 1 อาคาร 16 ชั้น รวม 332 ยูนิต ตั้งอยู่บนถนนพหลโยธิน ใกล้มหาวิทยาลัยเกษตรศาสตร์ พัฒนาโดย Origin Property K.S.Manufactory (1991) ดูแลงานเปลือกอาคารทุกอาคาร",
    highlightsTh: [
      "3 อาคาร (20+20+16 ชั้น) 332 ยูนิต",
      "ใกล้มหาวิทยาลัยเกษตรศาสตร์",
      "ย่านพหลโยธิน–เสนานิคม",
    ],
  },
  {
    slug: "the-origin-saphanmai",
    name: "The Origin Saphan Mai",
    image: "/images/project-the-origin-saphanmai.png",
    type: "Mid-rise Condominium",
    typeTh: "คอนโดมิเนียม Mid-rise",
    province: "Bangkok",
    provinceTh: "กรุงเทพมหานคร",
    location: "Sai Mai, Bangkok",
    locationTh: "ถนนพหลโยธิน เขตสายไหม กรุงเทพมหานคร",
    year: "2020",
    developer: "Origin Property",
    scope: ["Aluminium Door & Window", "Stickwall System", "Railing"],
    descriptionTh:
      "คอนโดมิเนียม Mid-rise สูง 14 ชั้น 536 ยูนิต บนถนนพหลโยธินย่านสะพานใหม่–สายไหม ใกล้สถานี BTS สายใหม่ พัฒนาโดย Origin Property ภายใต้แบรนด์ The Origin K.S.Manufactory (1991) ดูแลงานระบบ Stickwall และประตู–หน้าต่างอลูมิเนียม",
    highlightsTh: [
      "อาคารสูง 14 ชั้น 536 ยูนิต",
      "ย่านสะพานใหม่–สายไหม",
      "ระบบ Stickwall ครบระบบ",
    ],
  },
  {
    slug: "holiday-inn-suite-leamchabang",
    name: "Holiday Inn & Suites Siracha Laemchabang",
    image: "/images/project-holiday-inn-suite-leamchabang.png",
    type: "Hotel",
    typeTh: "โรงแรม",
    province: "Chonburi",
    provinceTh: "ชลบุรี",
    location: "Si Racha, Chonburi",
    locationTh: "ถนนสุขุมวิท อำเภอศรีราชา จังหวัดชลบุรี",
    year: "2020",
    developer: "IHG",
    scope: [
      "Aluminium Door & Window",
      "Unitized Curtain Wall",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "โรงแรมในเครือ Holiday Inn & Suites Siracha Laemchabang โรงแรม 4 ดาวในเครือ IHG จำนวน 347 ห้องพัก ตั้งอยู่บนถนนสุขุมวิทย่านแหลมฉบัง–ศรีราชา ใกล้มหาวิทยาลัยเกษตรศาสตร์ วิทยาเขตศรีราชา K.S.Manufactory (1991) ดูแลงานเปลือกอาคาร ประตู–หน้าต่างอลูมิเนียม และระบบกระจกทั้งอาคาร",
    highlightsTh: [
      "โรงแรม 4 ดาว 347 ห้อง",
      "แบรนด์ IHG · Holiday Inn & Suites",
      "งานเปลือกอาคารเกรด Hospitality",
    ],
  },
  {
    slug: "holiday-inn-express-rayong",
    name: "Holiday Inn Express Rayong",
    image: "/images/project-holiday-inn-express-rayong.png",
    type: "Hotel",
    typeTh: "โรงแรม",
    province: "Rayong",
    provinceTh: "ระยอง",
    location: "Mueang Rayong",
    locationTh: "อำเภอเมืองระยอง จังหวัดระยอง",
    year: "2020",
    developer: "IHG",
    scope: ["Aluminium Door & Window", "Glass Wall", "Railing"],
    descriptionTh:
      "โรงแรม Holiday Inn Express ในเครือ IHG ย่านเมืองระยอง ใกล้เขตอุตสาหกรรมและแหล่งท่องเที่ยวหลักของระยอง K.S.Manufactory (1991) ดูแลงานเปลือกอาคารและประตู–หน้าต่างอลูมิเนียมของโรงแรมทั้งระบบ เน้นความเรียบร้อยและคุณภาพในมาตรฐานโรงแรม",
    highlightsTh: [
      "โรงแรมในเครือ IHG",
      "ย่านเมืองระยอง",
      "งานเปลือกอาคารเกรด Hospitality",
    ],
  },
  {
    slug: "knightsbridge-phaholyothin-interchange",
    name: "KnightsBridge Phaholyothin Interchange",
    image: "/images/project-knightsbridge-phaholyothin-interchange.png",
    type: "Mid-rise Condominium",
    typeTh: "คอนโดมิเนียม Mid-rise",
    province: "Bangkok",
    provinceTh: "กรุงเทพมหานคร",
    location: "Anusawari, Bang Khen",
    locationTh: "แขวงอนุสาวรีย์ เขตบางเขน กรุงเทพมหานคร",
    year: "2019",
    developer: "Origin Property",
    scope: ["Aluminium Door & Window", "Stickwall System", "Railing"],
    descriptionTh:
      "คอนโดมิเนียม Mid-rise สูง 14 ชั้น รวม 726 ยูนิต ย่านวงเวียนหลักสี่ ถนนพหลโยธิน ใกล้ BTS สายสีเขียวและรถไฟฟ้าสายสีชมพู พัฒนาโดย Origin Property K.S.Manufactory (1991) รับงานระบบ Stickwall และประตู–หน้าต่างอลูมิเนียม",
    highlightsTh: [
      "อาคารสูง 14 ชั้น 726 ยูนิต",
      "ย่านวงเวียนหลักสี่ พหลโยธิน",
      "ใกล้ BTS สายสีเขียวและสายสีชมพู",
    ],
  },
  {
    slug: "notting-hill-jatujak-interchange",
    name: "Notting Hill Jatujak - Interchange",
    image: "/images/project-notting-hill-jatujak.png",
    type: "Low-rise Condominium",
    typeTh: "คอนโดมิเนียม Low-rise",
    province: "Bangkok",
    provinceTh: "กรุงเทพมหานคร",
    location: "Chomphon, Chatuchak",
    locationTh: "ซอยพหลโยธิน 18 แขวงจอมพล เขตจตุจักร กรุงเทพมหานคร",
    year: "2018",
    developer: "Origin Property",
    scope: ["Aluminium Door & Window", "Glass Wall", "Railing"],
    descriptionTh:
      "คอนโดมิเนียม Low-rise สูง 8 ชั้น 156 ยูนิต ตั้งอยู่ในซอยพหลโยธิน 18 ย่านจตุจักร ใกล้ BTS หมอชิต–สะพานควาย พัฒนาโดย Origin Property ภายใต้แบรนด์ Notting Hill K.S.Manufactory (1991) รับงานติดตั้งเปลือกอาคารอลูมิเนียม",
    highlightsTh: [
      "อาคารสูง 8 ชั้น 156 ยูนิต",
      "ซอยพหลโยธิน 18",
      "ใกล้ BTS หมอชิต–สะพานควาย",
    ],
  },
  {
    slug: "kensington-leamchabang-sriracha",
    name: "Kensington Leamchabang-Sriracha",
    image: "/images/project-kensington-leamchabang-sriracha.png",
    type: "Low-rise Condominium",
    typeTh: "คอนโดมิเนียม Low-rise",
    province: "Chonburi",
    provinceTh: "ชลบุรี",
    location: "Thung Sukhla, Si Racha",
    locationTh: "ตำบลทุ่งสุขลา อำเภอศรีราชา จังหวัดชลบุรี",
    year: "2018",
    developer: "Origin Property",
    scope: ["Aluminium Door & Window", "Glass Wall", "Railing"],
    descriptionTh:
      "คอนโดมิเนียม Low-rise 2 อาคาร สูง 8 ชั้น 399 ยูนิต บนถนนสุขุมวิทย่านแหลมฉบัง–ศรีราชา ตอบโจทย์พนักงานในนิคมอุตสาหกรรมแหลมฉบัง พัฒนาโดย Origin Property ภายใต้แบรนด์ Kensington K.S.Manufactory (1991) ดูแลงานเปลือกอาคารครบวงจร",
    highlightsTh: [
      "2 อาคาร 8 ชั้น 399 ยูนิต",
      "ถนนสุขุมวิท แหลมฉบัง",
      "ใกล้นิคมอุตสาหกรรมแหลมฉบัง",
    ],
  },
  {
    slug: "the-contrast-condominium",
    name: "The Contrast Condominium & The Contrast I Hotel",
    image: "/images/project-the-contrast.png",
    type: "Condominium + Hotel",
    typeTh: "คอนโดมิเนียมและโรงแรม",
    province: "Rayong",
    provinceTh: "ระยอง",
    location: "Pluak Daeng, Rayong",
    locationTh: "อำเภอปลวกแดง จังหวัดระยอง",
    year: "2014",
    developer: "Tam Tawan Land",
    scope: ["Aluminium Door & Window", "Glass Wall", "Railing"],
    descriptionTh:
      "โครงการ mixed-use ประกอบด้วย The Contrast Condominium และ The Contrast I Hotel ในย่านปลวกแดง ระยอง ใกล้นิคมอุตสาหกรรมอีสเทิร์นซีบอร์ด ตอบโจทย์พนักงานและผู้บริหารที่ทำงานในพื้นที่ K.S.Manufactory (1991) ดูแลงานเปลือกอาคารทั้งส่วนคอนโดและโรงแรม",
    highlightsTh: [
      "คอนโด + โรงแรมในโครงการเดียวกัน",
      "ใกล้นิคมอุตสาหกรรมอีสเทิร์นซีบอร์ด",
      "ย่านปลวกแดง ระยอง",
    ],
  },
  {
    slug: "casa-condominium",
    name: "CASA Condominium",
    image: "/images/project-casa-condominium.png",
    type: "Low-rise Condominium",
    typeTh: "คอนโดมิเนียม Low-rise",
    province: "Chonburi",
    provinceTh: "ชลบุรี",
    location: "Chonburi",
    locationTh: "จังหวัดชลบุรี",
    year: "2019",
    developer: "Private Developer",
    scope: ["Aluminium Door & Window", "Glass Wall", "Railing"],
    descriptionTh:
      "โครงการคอนโดมิเนียม Low-rise ในย่านชลบุรี ออกแบบภายใต้สไตล์ร่วมสมัย ตอบโจทย์คนทำงานและครอบครัวในพื้นที่ K.S.Manufactory (1991) รับผิดชอบงานติดตั้งประตู–หน้าต่างอลูมิเนียม ผนังกระจก และราวกันตกตลอดทั้งโครงการ",
    highlightsTh: [
      "คอนโดมิเนียม Low-rise ย่านชลบุรี",
      "ดีไซน์ร่วมสมัย",
      "งานเปลือกอาคารครบระบบ",
    ],
  },
  {
    slug: "sport-development-learning-center",
    name: "ศูนย์พัฒนาสมรรถภาพและการเรียนรู้",
    image: "/images/project-sport-learning-center.png",
    type: "Institutional Building",
    typeTh: "อาคารสถาบัน",
    province: "Thailand",
    provinceTh: "ประเทศไทย",
    location: "Thailand",
    locationTh: "ประเทศไทย",
    year: "2021",
    developer: "Government Project",
    scope: [
      "Aluminium Door & Window",
      "Stickwall System",
      "Glass Wall",
      "Skylight",
      "Railing",
    ],
    descriptionTh:
      "โครงการก่อสร้างศูนย์พัฒนาสมรรถภาพและการเรียนรู้ อาคารสถาบันสำหรับการพัฒนาบุคลากรและกิจกรรมเรียนรู้ งานเปลือกอาคารต้องรองรับการใช้งานทั้งห้องบรรยาย ห้องฝึกปฏิบัติการ และพื้นที่กิจกรรม K.S.Manufactory (1991) ดูแลงานระบบกระจกอลูมิเนียมครบระบบเพื่อให้ได้อาคารที่ทั้งสวยงามและทนทาน",
    highlightsTh: [
      "อาคารสถาบันของหน่วยงานรัฐ",
      "งาน Stickwall, Glass Wall, Skylight",
      "ออกแบบเพื่อการเรียนรู้และกิจกรรม",
    ],
  },
  {
    slug: "aviation-personnel-training-building",
    name: "อาคารเรียนศูนย์พัฒนาบุคลากรด้านการบิน",
    image: "/images/project-aviation-training-center.png",
    type: "Institutional Building",
    typeTh: "อาคารสถาบันด้านการบิน",
    province: "Thailand",
    provinceTh: "ประเทศไทย",
    location: "Thailand",
    locationTh: "ประเทศไทย",
    year: "2020",
    developer: "Government Project",
    scope: [
      "Aluminium Door & Window",
      "Stickwall System",
      "Glass Wall",
      "Railing",
    ],
    descriptionTh:
      "อาคารเรียนศูนย์พัฒนาบุคลากรด้านการบิน โครงการภาครัฐสำหรับการฝึกอบรมบุคลากรในอุตสาหกรรมการบิน งานเปลือกอาคารต้องออกแบบให้รองรับการใช้งานระดับสถาบันการศึกษา และทนต่อสภาพอากาศในบริเวณสนามบิน K.S.Manufactory (1991) ดูแลงาน Stickwall, ประตู–หน้าต่างอลูมิเนียม และราวกันตกทั้งโครงการ",
    highlightsTh: [
      "อาคารเรียนสำหรับอุตสาหกรรมการบิน",
      "โครงการภาครัฐ",
      "งาน Stickwall และประตู–หน้าต่างอลูมิเนียมครบระบบ",
    ],
  },
];

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
